import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import TopNavBar from "../components/TopNavBar";
import { Toaster } from "@/components/ui/sonner";
import "../app/globals.css";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black min-h-screen`}
      >
        <SessionProvider>
          <TopNavBar />
          <main className="flex flex-col flex-1 min-h-[calc(100vh-4rem)]">{children}</main>
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
